github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/alibaba-dragonwell"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            JDK 8
  id:              jdk
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_Extended.*[\d\.]+_x64_linux.tar.gz$
    repository: dragonwell8
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JDK 11
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_Extended.*[\d\.]+_x64_linux.tar.gz$
    repository: dragonwell11
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_.*[\d\.+]+_x64_linux.tar.gz$
    repository: dragonwell17
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name:            JDK 21
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_.*[\d\.+]+_x64_linux.tar.gz$
    repository: dragonwell21
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

# ARM64
- name:            JDK 8 ARM64
  id:              jdk
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  cpe_pattern:     "update[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_Extended.*[\d\.]+_aarch64_linux.tar.gz$
    repository: dragonwell8
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch:       arm64
- name:            JDK 11 ARM64
  id:              jdk
  version_pattern: "11\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_Extended.*[\d\.]+_aarch64_linux.tar.gz$
    repository: dragonwell11
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch:       arm64
- name:            JDK 17 ARM64
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_.*[\d\.+]+_aarch64_linux.tar.gz$
    repository: dragonwell17
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch:       arm64
- name:            JDK 21 ARM64
  id:              jdk
  version_pattern: "21\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/alibaba-dragonwell-dependency:main
  with:
    glob:       Alibaba_Dragonwell_.*[\d\.+]+_aarch64_linux.tar.gz$
    repository: dragonwell21
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
    arch:       arm64
